export interface MatchFactGoal {
  minute: number;
  player: string;
  team: 'home' | 'away';
  isPenalty?: boolean;
  isOwnGoal?: boolean;
}

export interface MatchFactCard {
  minute: number;
  player: string;
  team: 'home' | 'away';
  type: 'yellow' | 'red';
}

export interface StructuredMatchFacts {
  fixtureId: string;
  homeTeam: string;
  awayTeam: string;
  leagueName: string;
  leagueSlug: string;
  matchDate: string;
  stadium?: string;
  homeScore?: number;
  awayScore?: number;
  status: 'finished' | 'scheduled' | 'live';
  goals?: MatchFactGoal[];
  cards?: MatchFactCard[];
  possession?: { home: number; away: number };
  shotsOnTarget?: { home: number; away: number };
  keyStatsSummary?: string;
  coverImageUrl?: string;
}

export interface GeneratedArticleDraft {
  title: string;
  slug: string;
  excerpt: string;
  body: string;
  cover_image_url: string;
  is_ai_generated: boolean;
  ai_reviewed: boolean;
  ai_source_data: StructuredMatchFacts;
  author_name: string;
}

/**
 * Generates an original Laku Media Sports match report, preview, or roundup
 * strictly derived from structured sports-data facts.
 */
export function generateSportsArticleFromData(
  facts: StructuredMatchFacts,
  type: 'match_report' | 'preview' | 'roundup' = 'match_report'
): GeneratedArticleDraft {
  const timestamp = Date.now();
  const coverUrl =
    facts.coverImageUrl ||
    'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80';

  if (type === 'preview') {
    const title = `PREVIEW: ${facts.homeTeam} vs ${facts.awayTeam} — ${facts.leagueName} Clash`;
    const slug = `${facts.homeTeam.toLowerCase()}-vs-${facts.awayTeam.toLowerCase()}-preview-${timestamp}`.replace(/[^a-z0-9-]/g, '-');
    const excerpt = `${facts.homeTeam} host ${facts.awayTeam} in a crucial ${facts.leagueName} showdown at ${facts.stadium || 'the stadium'}. Here is the complete data breakdown and match preview.`;

    const body = `
# PREVIEW: ${facts.homeTeam} vs ${facts.awayTeam} — ${facts.leagueName}

**Fixture Date:** ${facts.matchDate}  
**Venue:** ${facts.stadium || 'Home Ground'}  
**Competition:** ${facts.leagueName}

---

### Match Overview & Data Analysis

An intense ${facts.leagueName} battle awaits as **${facts.homeTeam}** square off against **${facts.awayTeam}**. Both sides come into this fixture seeking maximum points to bolster their league standings.

### Tactical & Statistical Snapshot

- **Home Side:** ${facts.homeTeam} will look to capitalize on home advantage and control tempo from the opening whistle.
- **Visiting Side:** ${facts.awayTeam} enter as formidable opponents looking to make a decisive statement on enemy territory.
- **Match Status:** Scheduled for kickoff on ${facts.matchDate}.

---

*Draft generated by Laku Media Sports Desk AI Pipeline based on official fixture records. Pending editorial review.*
`.trim();

    return {
      title,
      slug,
      excerpt,
      body,
      cover_image_url: coverUrl,
      is_ai_generated: true,
      ai_reviewed: false,
      ai_source_data: facts,
      author_name: 'Laku Media Sports Desk',
    };
  }

  // Finished Match Report
  const home = facts.homeTeam;
  const away = facts.awayTeam;
  const hScore = facts.homeScore ?? 0;
  const aScore = facts.awayScore ?? 0;
  const isDraw = hScore === aScore;
  const winner = hScore > aScore ? home : away;
  const loser = hScore > aScore ? away : home;

  const resultPhrase = isDraw
    ? `${home} and ${away} Battled to a ${hScore}-${aScore} Draw`
    : `${winner} Defeat ${loser} ${Math.max(hScore, aScore)}-${Math.min(hScore, aScore)}`;

  const title = `MATCH REPORT: ${resultPhrase} in ${facts.leagueName}`;
  const slug = `${home.toLowerCase()}-vs-${away.toLowerCase()}-match-report-${timestamp}`.replace(/[^a-z0-9-]/g, '-');
  
  const goalSummary = facts.goals && facts.goals.length > 0
    ? facts.goals.map((g) => `${g.player} (${g.minute}')`).join(', ')
    : 'No official goal details logged';

  const excerpt = `${resultPhrase} in a thrilling ${facts.leagueName} encounter. Key statistics, goal updates, and match breakdown.`;

  const goalsSection = facts.goals && facts.goals.length > 0
    ? facts.goals
        .map(
          (g) =>
            `- **${g.minute}'** — ⚽ **${g.player}** (${g.team === 'home' ? home : away})${
              g.isPenalty ? ' [Penalty]' : ''
            }${g.isOwnGoal ? ' [Own Goal]' : ''}`
        )
        .join('\n')
    : '- No goals scored or goalscorer detail not attached.';

  const cardsSection = facts.cards && facts.cards.length > 0
    ? facts.cards
        .map(
          (c) =>
            `- **${c.minute}'** — ${c.type === 'red' ? '🟥' : '🟨'} **${c.player}** (${c.team === 'home' ? home : away})`
        )
        .join('\n')
    : '- Clean disciplinary record in this fixture.';

  const possessionText = facts.possession
    ? `Possession finished **${home} ${facts.possession.home}% — ${facts.possession.away}% ${away}**.`
    : 'Match control stats confirmed at full-time whistle.';

  const body = `
# MATCH REPORT: ${resultPhrase}

**Final Score:** ${home} **${hScore} — ${aScore}** ${away}  
**Competition:** ${facts.leagueName}  
**Match Date:** ${facts.matchDate}  
${facts.stadium ? `**Stadium:** ${facts.stadium}` : ''}

---

### Executive Match Summary

${
  isDraw
    ? `**${home}** and **${away}** shared the spoils in an evenly contested ${facts.leagueName} clash ending **${hScore}-${aScore}** at the final whistle.`
    : `**${winner}** claimed all three points after securing a **${hScore}-${aScore}** victory over **${loser}** in their ${facts.leagueName} encounter.`
} ${possessionText}

---

### Key Match Timeline & Goals

${goalsSection}

---

### Disciplinary & Cards Summary

${cardsSection}

---

### Key Match Statistics

- **Final Score:** ${home} ${hScore} : ${aScore} ${away}
${facts.shotsOnTarget ? `- **Shots on Target:** ${home} ${facts.shotsOnTarget.home} | ${facts.shotsOnTarget.away} ${away}` : ''}
${facts.keyStatsSummary ? `- **Stats Note:** ${facts.keyStatsSummary}` : ''}

---

*This article was automatically generated by Laku Media Sports Desk using verified match fixture data. Subject to mandatory human review prior to publication.*
`.trim();

  return {
    title,
    slug,
    excerpt,
    body,
    cover_image_url: coverUrl,
    is_ai_generated: true,
    ai_reviewed: false,
    ai_source_data: facts,
    author_name: 'Laku Media Sports Desk',
  };
}
